homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.story3, name='story3'),
    path('Contacts/', views.contacts, name='contacts'),
    path('story1/', views.story1, name='story1'),
    path('CreateMatkul/', views.matkulAdd, name='matkulAdd'),
    path('Matkul/', views.matkul, name='matkul'),
    # path('Matkul/<int:my_id>/', views.MatkulDetail, name='matkulDetail'),
    # path('Matkul/<int:my_id>/delete', views.DeleteView, name='deleteView'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

class Matkul(models.Model) :
    title = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    sks = models.PositiveSmallIntegerField()
    description = models.TextField()
    semester = models.PositiveIntegerField()
    room = models.CharField(max_length=10)


    def __str__(self):
        return self.title

homepage/forms.py
from django import forms
from .models import Matkul

class ProductForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'title',
            'dosen',
            'sks',
            'description',
            'semester',
            'room'
        ]

homepage/views.py
from django.shortcuts import render, redirect
from .forms import ProductForm
from .models import Matkul

# Create your views here.
def story1(request):
    return render(request, 'story1.html')


def story3(request):
    return render(request, 'Story3.html')


def contacts(request):
    return render(request, 'Contacts.html')


def matkul(request):
    obj = Matkul.objects.all()
    context = {
        'object': obj
    }
    return render(request, "Matkul.html", context)


def matkulAdd(request):
    form = ProductForm(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('homepage:matkul')

    context = {
        'form': form
    }
    return render(request, "CreateMatkul.html", context)


# def MatkulDetail(request, my_id):
#     obj = Matkul.objects.get(id=my_id)
#     context = {
#         'object':obj
#     }
#     return render(request, "MatkulDetail.html", context)


# def DeleteView(request, my_id):
#     Matkul.objects.get(id=my_id).delete()
#     return redirect('story1')

homepage/templates/Contacts.html
{% extends 'base.html' %}

    {% block content %}

    <body style="background-color:  rgba(98,82,97,1)">
        <div class="container-fluid">
            <div class="row" >
            <div class="col-sm">
                <div class="contactsFrame2">
                    <span class="contactsFont2">Contacts</span>
                </div>
            </div>
            </div>
            
            <div class="row">
                <div class="col-sm">
                    <div class="gitlabFrame"><span class="gitlabFont">www.gitlab.com/AdrianChandraRachman</span></div>
                    <div class="gitImage"></div>
                    <div class="linkedinFrame"><span class="linkedinFont">www.linkedin.com/in/adrian-chandra-rachman-883b6a1a3/</span></div>
                    <div class="linkedinImage"></div>
                    <div class="emailFrame"><span class="emailFont">adriancrachman02@gmail.com</span></div>
                    <div class="emailImage"></div>
                </div>
                <div class="col-sm">
                    <div class="instaFrame"><span class="instaFont">www.instagram.com/adriancrachman/</span></div>
                    <div class="instagramImage"></div>
                    <div class="phoneFrame"><span class="phoneFont">081293322267</span></div>
                    <div class="phoneImage"></div>
                </div>
            </div>

            <div class="row">
                <div class="whatsappFrame"></div>
                <div class="telegramFrame"></div>
                <div class="lineFrame"></div>
                <div class="lineImage"></div>
                <div class="whatsappImage"></div>
                <div class="telegramImage"></div>
            </div>
        </div>
    </body>

    {% endblock %}
    

homepage/templates/CreateMatkul.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}
    <body style="background-color:  rgba(98,82,97,1)">
            <form method = "POST" >
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Save"> 
            </form>
        </body>
{% endblock %}

homepage/templates/Matkul.html
{% extends 'base.html' %}

{% load static %}

    

{% block content %}

    <body style="background-color:  rgba(98,82,97,1)">
        {% for i in object %}
            <div class="card" style="width: 18rem; margin: 3%;"> 
                <div class="card-body">
                <h5 class="card-title">{{i.title}}</h5>
                <p class="card-text">Lecturer: {{i.dosen}}</p>
                <p class="card-text">SKS: {{i.sks}}</p>
                <p class="card-text">Desc: {{i.description}}</p>
                <p class="card-text">Semester: {{i.semester}}</p>
                <p class="card-text">Room: {{i.room}}</p>
                {% comment %} <a href="{% url 'MatkulDetail' my_id=i.id %}" class="btn btn-primary">View Details</a>
                <a href="{% url 'DeleteView' my_id=i.id %}" class="btn btn-warning">Delete</a> {% endcomment %}
                </div>
            </div><br>
        {% endfor %}
    </body>

{% endblock %}

homepage/templates/MatkulDetail.html
{% extends 'base.html' %}

{% load static %}

    

{% block content %}

    <body style="background-color:  rgba(98,82,97,1)">

        {% for i in object %}
            <div class="card" style="width: 18rem; margin: 3%;"> 
                <div class="card-body">
                <h5 class="card-title">{{i.title}}</h5>
                <p class="card-text">{{i.description}}</p>
                <a href="{% url 'MatkulDetail' my_id=i.id %}" class="btn btn-primary">View Details</a>
                <a href="{% url 'DeleteView' my_id=i.id %}" class="btn btn-warning">Delete</a>
                </div>
            </div>
        {% endfor %}


    </body>

{% endblock %}

homepage/templates/Story3.html
{% extends 'base.html' %}

    {% block content %}

    <body style="background-color:  rgba(98,82,97,1);">
        <div class = "container-fluid">
            <div class="row">
                
                <div class="col-6">
                    <div class="nameFrame">
                        <span class="nameFont">Adrian Chandra Rachman</span>
                    </div>
                    
                    <div class="aboutMeFrame">
                        <span class="aboutMeFont">
                        <b>About me :</b><br>
                        My name is Adrian. I’m a student of the Faculty of Computer Science majoring in Information Systems.
                        </span>
                    </div>
                    
                    <div class="workExperienceFrame">
                        <span class="workExperienceFont">
                        <b>Work Experience :</b><br>
                        Mentor for DDP0: I taught programming with python to the freshman of Fasilkom UI.
                        </span>
                    </div>
                    
                    <div class="skillsFrame">
                        <span class="skillsFont">
                        <b>Skillsets & Tools :</b><br>
                        Excel, Python (Programming Language), Word, Java (Programming Language), Powerpoint, Table Tennis (Sport).
                        </span>
                    </div>
                    
                </div>

                <div class="col-sm">
                    <div class="photo"></div>

                    <div class="educationFrame">
                        <span class="educationFont">
                        <b>Education:</b><br>
                        University of Indonesia 
                        (2019 - Present) <br>
                        SMAN 70 Jakarta
                        (2016 - 2019) <br>
                        SMP Cenderawasih 1
                        (2013 - 2016)<br>
                        </span>
                    </div> 
                    
                    <div class="languageFrame">
                        <span class="languageFont">
                        <b>Language Proficiency :</b><br>
                        - English (Professional) <br>
                        - Indonesian (Native)
                        </span>
                    </div>
                    
                    <a href="{% url 'homepage:contacts' %}">
                    <div class="contactsFrame">
                        
                        <span class="contactsFont"><b>Contacts</b></span>
                    </div>
                    </a>
                   
                    
                </div>

            </div>
        </div>
    </body>

    {% endblock %}

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{% static './main.css' %}" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
        <title>Document</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Stories
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/story1">Story1</a>
                    <a class="dropdown-item" href="/">Story3</a>
                    <a class="dropdown-item" href="/Matkul">Matkul</a>
                    <a class="dropdown-item" href="/CreateMatkul">Create Matkul</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/Contacts">Contacts</a>
                  </div>
                </li>
              </ul>
            </div>
          </nav>

          {% block content %}
          
          {% endblock %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
    

homepage/templates/story1.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <body>
        <h1>Profile | Story 1</h1>

        <div align="center" >
            <img class="pic" src="{% static 'adrian.jpg' %}">
        </div>
        
        
        <div id="bio">
            <div style="text-align: center;">   
                <h1>Adrian Chandra Rachman</h1>
                <h2>Information Systems 2019</h2>
                <h2>University of Indonesia</h2>
                <h3>1906399575</h3>
            </div>

            <dl>
                <dt><b>Hobbies:</b></dt>
                <dd><li>Table Tennis</li></dd>
                <dd><li>Reading</li></dd>
                <dd><li>Baking</li></dd>
                <dd><li>Brewing Coffee</li></dd>
                <dd><li>Playing Online Games</li></dd>
            </dl>

            <dl>
                <dt><b>Education:</b></dt>
                <dd><li>SMP Cenderawasih 1 (2013 - 2016)</li></dd>
                <dd><li>SMAN 70 Jakarta (2016 - 2019)</li></dd>
                <dd><li>University of Indonesia (2019 - Present)</li></dd>
            </dl>

            <b>Desc:</b><br>
                I'm a Information Systems student in the <br>
                Faculty of Computer Science at the University <br>
                of Indonesia. I plan on building my own business <br>
                when i'm done with university or perhaps when i'm still <br>
                studying. I'm hard working, kind, and love to work in teams.<br>

            <br><b>Social Media:</b><br>
            https://www.linkedin.com/in/adrian-chandra-rachman-883b6a1a3/ <br>
            https://www.instagram.com/adriancrachman/?hl=id <br>

        </div>

    </body>
{% endblock %}